name: Build Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --add-data "config.json;." --name "jianying-tools" jianying.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: jianying-tools-exe
          path: dist/jianying-tools.exe 